catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import ProductListView, CategoryListView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ProductDetailView
from . import views
from .apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='product'),
    path('index/', CategoryListView.as_view(), name='index'),
    path('contacts/', views.contacts, name='contacts'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('detail/<int:pk>/', ProductDetailView.as_view(), name='detail_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('catalog/<int:page>/', cache_page(60)(ProductListView.as_view()), name='detail_category'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('blogging/', include('blogging.urls')),
    path('smm/', include('smm.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smm/urls.py
from django.urls import path
from smm.apps import SmmConfig
from smm.views import *

app_name = SmmConfig.name

urlpatterns = [
    # path('', ServiceClientListView.as_view(), name='list'),
    # path('smm_create/', ServiceClientCreateView.as_view(), name='create'),
    # path('smm_detail/<int:pk>/', ServiceClientDetailView.as_view(), name='detail'),
    # path('smm_update/<int:pk>/', ServiceClientUpdateView.as_view(), name='update'),
    # path('smm_delete/<int:pk>/', ServiceClientDeleteView.as_view(), name='delete'),

    path('news_letter_list/', NewsletterListView.as_view(), name='letter_list'),
    path('news_letter_create/', NewsletterCreateView.as_view(), name='letter_create'),
    path('news_letter_detail/<int:pk>/', NewsletterDetailView.as_view(), name='letter_detail'),
    path('news_letter_update/<int:pk>/', NewsletterUpdateView.as_view(), name='letter_update'),
    path('news_letter_delete/<int:pk>/', NewsletterDeleteView.as_view(), name='letter_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_detail/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),

    path('mailinglogs_list', MailinglogsListView.as_view(), name='mailinglogs_list'),
    path('mailinglogs_create/', MailinglogsCreateView.as_view(), name='mailinglogs_create'),
    path('mailinglogs_detail/<int:pk>/', MailinglogsDetailView.as_view(), name='mailinglogs_detail'),
    path('mailinglogs_update/<int:pk>/', MailinglogsUpdateView.as_view(), name='mailinglogs_update'),
    path('mailinglogs_delete/<int:pk>/', MailinglogsDeleteView.as_view(), name='mailinglogs_delete'),
]

catalog/models.py
from django.db import models

from user.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='наименование')
    category_description = models.CharField(max_length=100, verbose_name='описание')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.category_name} {self.category_description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('category_name',)


class Product(models.Model):
    product_name = models.CharField(max_length=100, verbose_name='наименование')
    product_description = models.CharField(max_length=100, verbose_name='описание')
    img = models.ImageField(verbose_name='превью', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    product_prise = models.IntegerField(default=0, verbose_name='Цена')
    product_prise_name = models.CharField(max_length=100, verbose_name='необязательное поле')
    product_date = models.DateTimeField(auto_now_add=True)
    product_last = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f'{self.product_name} {self.product_description}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('product_name',)


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50)
    version_name = models.CharField(max_length=100)
    current_version = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.product} {self.version_number} {self.current_version}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('version_number',)

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    img = models.ImageField(verbose_name='аватар', **NULLABLE)
    phone_number = models.CharField(max_length=20, verbose_name='телефон')
    country = models.CharField(max_length=20, verbose_name='страна')
    email = models.EmailField(verbose_name='почта', unique=True)
    email_verification_token = models.CharField(max_length=255, null=True, blank=True)
    is_email_verified = models.BooleanField(default=False)
    fullname = models.CharField(max_length=500, verbose_name='ФИО'),
    comment = models.TextField(max_length=1000, verbose_name='Комментарий', **NULLABLE),

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.phone_number} {self.country}'

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'product_description', 'img', 'category', 'product_prise']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('product_name')
        description = cleaned_data.get('product_description')
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция',
                           'радар']
        for word in forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError("Запрещенное слово в названии или описании продукта")


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['version_number', 'version_name', 'product']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

catalog/views.py
from linecache import cache

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Version, Category
from config import settings


class ProductListView(ListView):
    model = Product
    template_name = 'catalog/product.html'

    # def get_queryset(self):
    #    queryset = super().get_queryset()
    #    active_versions = Version.objects.filter(current_version=True)
    #    active_product_ids = active_versions.values_list('product__id', flat=True)
    #    queryset = queryset.filter(id__in=active_product_ids)
    #    return queryset


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    login_url = 'user:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')
    login_url = 'user:login'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product')
    login_url = 'user:login'


class CategoryListView(ListView):
    model = Product
    template_name = 'catalog/index.html'


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({phone}) {message}')
    return render(request, 'catalog/contacts.html')


@login_required
def edit_product(request, product_id):
    # Получение продукта по идентификатору
    product = get_object_or_404(Product, id=product_id)

    if product.owner == request.user:
        # Проверка, что текущий пользователь является владельцем продукта
        # Обработка случая, когда пользователь пытается изменить чужой продукт
        return redirect('product_list')

    if request.method != 'POST':
        # Отображение формы редактирования продукта
        return render(request, 'user/edit_product.html', {'product': product})
    form = UserCreationForm(request.POST)
    if form.is_valid():
        pass
    return redirect('product_list')


def get_category_data():
    if settings.CACHE_ENABLED:
        key = 'category_list'
        category_list = cache.get(key)
        if category_list is None:
            print('No category cache detected. I gonna cache it')
            category_list = Category.objects.all()
            cache.set(key, category_list)
    else:
        category_list = Category.objects.all()
    return category_list


class CategoryView(ListView):
    model = Category

    def get_queryset(self, *args, **kwargs):
        return get_category_data()

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <title>Computer world Shop</title>

    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
</head>

<body>


<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Computer world</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'catalog:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blogging:create' %}">Blog Сreate</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="{% url 'blogging:list' %}">Blog</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Entrance</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'user:logout' %}">Выйти</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'user:login' %}">Войти</a>
                    <a class="dropdown-item" href="{% url 'user:register' %}">Зарегистрироваться</a>
                    {% endif %}

                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">Dropdown</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'catalog:product' %}">Каталог</a>
                    <a class="dropdown-item" href="{% url 'catalog:contacts' %}">Контакты</a>
                     <a class="dropdown-item" href="{% url 'user:user_list' %}">Менеджер</a>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
    </div>
</nav>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Computer world Shop</h1>
            <p>Добро пожаловать!
                Это магазин современных решений в мире персональных компьютеров и комплектующих Computer world.
            </p>
            <p><a class="btn btn-secondary btn-lg" href="{% url 'catalog:contacts' %}" role="button">Информация о нас!
                &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
        <hr>

    </div> <!-- /container -->

</main>

<footer class="container">
    <p>&copy; Company 2023</p>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_detail.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                Инфо продукта
                            </h4>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <div class="card-footer"></div>
                        </div>
                    </div>
                </div>
                {% if object %}
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">
                                    Предметы
                                </h4>
                            </div>
                            <div class="card-body">
                                <button type="submit" class="btn btn-success">Сохранить</button>
                                <div class="card-footer"></div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
    </div>

{% endblock %}

catalog/templates/catalog/contacts.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Computer world</title>
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-success border-bottom box-shadow">
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <h5 class="my-0 mr-md-auto font-weight-normal text-light">Computer world</h5>
        <a class="p-2 btn btn-outline-success" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-success" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center text-dark">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25 text-dark">Страна</td>
                            <td class="text-dark">USA</td>
                        </tr>
                        <tr>
                            <td class="w-25 text-dark">ИНН</td>
                            <td class="text-dark">91-1147775</td>
                        </tr>
                        <tr>
                            <td class="w-25 text-dark">Адрес</td>
                            <td class="text-dark"> Harper Hill,WA,98457-7955</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow text-dark">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-success">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                ComputerWorld
                <small class="d-block mb-3 text-warning">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-warning">
                    <li><a class="text-warning" href="#">Рассылки</a></li>
                    <li><a class="text-warning" href="#">Телеграм боты</a></li>
                    <li><a class="text-warning" href="#">Полезные утилиты</a></li>
                    <li><a class="text-warning" href="#">Веб-приложения</a></li>
                    <li><a class="text-warning" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-warning" href="#">Мы скоро здесь появиться<br>
                        что-то очень крутое</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-warning" href="/contacts/">Контакты<br>
                        +78005557595<br>
                        +74561458752</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Computer world</title>
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-success border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Computer world</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-info" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-info" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-warning">
    <h1 class="display-4">Computer world</h1>
    <p class="lead">Сomputer world - Блестящий магазин компьютеров,
        которые отлично подойдут как для игр, проведения стримов,
        для работы, и просто как часть интерьера</p>
</div>
<div class="text-center">
    <div class="row mt-5">
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal text-success">Cистемные блоки</h5>
                    </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title text-danger">От $250</h1>
                    <p class="card-text text-warning">Здесь дорогой друг ты найдешь ПК для любых целей</p>
                    <button type="button" class="btn btn-lg btn-block btn-outline-success">go over</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-success">(((((</button>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal text-success">Мониторы</h5>
                    </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title text-danger">От $250</h1>
                    <p class="card-text text-warning" >Здесь дорогой друг ты найдешь мониторы на любой вкус</p>
                     <button type="button" class="btn btn-lg btn-block btn-outline-success">go over</button>
                    <button type="button" class="btn btn-lg btn-block btn-outline-success">(((((</button>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <h5 class="my-0 font-weight-normal text-success">Бесподобный сервис</h5>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title text-danger">$ 100</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Лицензия ПО</li>
                        <li>- Поддержка</li>
                        <li>- Сборка и установка</li>
                        <li>- Доставка</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-success">Купить</button>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            ComputerWorld
            <small class="d-block mb-3 text-warning">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-warning">
                <li><a class="text-warning" href="#">Рассылки</a></li>
                <li><a class="text-warning" href="#">Телеграм боты</a></li>
                <li><a class="text-warning" href="#">Полезные утилиты</a></li>
                <li><a class="text-warning" href="#">Веб-приложения</a></li>
                <li><a class="text-warning" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-warning" href="#">Мы скоро здесь появиться<br>
                    что-то очень крутое</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-warning" href="/contacts/">Контакты<br>
                    +78005557595<br>
                    +74561458752</a></li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% load static %}
{% load my_tags %}
{% block content %}
    <div class="row">

        {% for object in object_list%}
            <div class="col-md-4">
                <div>
                    {{ object.product_description|truncatechars:500 }}
                </div>
                <div>
                    <img src="/media/{{ object.img }}" style="width: 250px;height: 150px"/>
                    <br>
                    <img src="{{ object.img|mediapath }}" style="width: 250px;height: 150px"/></img>
                </div>
            </div>



        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}

    <div class="col-12">
        <a class="btn btn-info" href="{% url 'catalog:create_product' %}">Добавить </a>
    </div>
    <div class="row mt-3">
        {% for object in object_list %}
        <div class="col-md-5 mt-1">
            <h4 class="card-title text-danger">{{ object.product_name }}
            </h4>
            <img src="{{ object.img|mediapath }}" style="width: 250px;height: 150px"/></img>
            {% for version_item in object.version_set.all %}
                <p>Актуальная версия:{{ version_item.version_number }}</p>
            {% endfor %}
                <h2 class="card-text text-dark">{{ object.product_prise_name }} {{ object.product_prise }} Рублёв</h2>
                <a href="#" class="btn btn-success">Купить</a>
                <a href="{% url 'catalog:detail_product' object.pk %}" type="button"
                   class="btn btn-success">Просмотр</a>

                <a href="{% url 'catalog:detail_category' object.pk %}" type="button"
                   class="btn btn-success">View</a>

                <a href="{% url 'catalog:update_product' object.pk %}" type="button"
                   class="btn btn-success">Обновить</a>
                <a href="{% url 'catalog:delete_product' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
                </div>
                <div class="col-md-5">
                    <a class="btn btn-info" href="#" role="button">{{ object.product_description }}</a>
                </div>
            {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}


{% block content %}
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    Удалить продукт
                </h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы уверены, что хотите удалить"{{ product.product_name }}"?</p>>
                    <button type="submit" class="btn btn-success">
                        Подтвердить
                    </button>
                    <a href="{% url 'catalog:product' %}" class="btn btn-danger"> Отмена </a>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}

    <div class="row mt-3">

        <div class="col-md-5 mt-1">
            <h4 class="card-title text-danger">{{ object.product_name }}
            </h4>
            <img src="{{ object.img|mediapath }}" style="width: 250px;height: 150px"/></img>
            <h2 class="card-text text-dark">{{ object.product_prise_name }} {{ object.product_prise }} Рублёв</h2>
            <a href="#" class="btn btn-success">Купить</a>

            <a href="{% url 'catalog:update_product' object.pk %}" type="button" class="btn btn-success">Обновить</a>
            <a href="{% url 'catalog:delete_product' object.pk %}" type="button" class="btn btn-danger">Удалить</a>
        </div>
        <div class="col-md-5">
            <a class="btn btn-info" href="#" role="button">{{ object.product_description }}</a>
        </div>

    </div>



{% endblock %}